import React, { useEffect, useState } from "react";
import { Helmet } from "react-helmet"
import { format } from 'date-fns';
import { utcToZonedTime } from 'date-fns-tz';
import logo from './logo.svg';
import './App.css';

const DATE_FORMAT_STYLE = "MM/dd HH:mm";

function App() {

  const [text, setText] = useState("");

  useEffect(() => {
    const text = format(utcToZonedTime(new Date(), "Asia/Tokyo"), DATE_FORMAT_STYLE)
    setText(text);
  }, []);

  const title = `Dynamic OGP | ${text}`;
  const description = `Generated by create next app | ${text}`;
  const imageUrl = `https://og-image.vercel.app/**OGP**%20${encodeURIComponent(text)}.png?theme=light&md=1&fontSize=100px&images=https%3A%2F%2Fassets.vercel.com%2Fimage%2Fupload%2Ffront%2Fassets%2Fdesign%2Fvercel-triangle-black.svg`;


  return (
    <div className="App">

      <Helmet>
        <title>{title}</title>
        <meta name="description" content={description} />

        <meta property="og:title" content={title} />
        <meta property="og:description" content={description} />
        <meta property="og:url" content="http://example.com/" />
        <meta property="og:type" content="website" />
        <meta property="og:image" content={imageUrl} />
        <meta property="og:image:width" content={1200} />
        <meta property="og:image:height" content={630} />

        <meta name="twitter:title" content={title} />
        <meta name="twitter:description" content={description} />
        <meta name="twitter:image" content={imageUrl} />
        <meta name="twitter:card" content="summary_large_image" />
      </Helmet>

      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>
          {text}
        </p>
      </header>
    </div>
  );
}

export default App;
